# SPDX-License-Identifier: GPL-2.0
i3c-y				:= device.o master.o
obj-$(CONFIG_I3C)		+= i3c.o
obj-$(CONFIG_I3C)		+= master/

# Samsung additions from Kbuild
obj-$(CONFIG_I3C_HCI_EXYNOS)		+= i3c-hci-exynos.o
