# SPDX-License-Identifier: GPL-2.0
# define_trace.h needs to know how to find our header
CFLAGS_trace.o				:= -I$(src)

obj-$(CONFIG_USB_DWC3)			+= dwc3.o

dwc3-y					:= core.o

ifneq ($(CONFIG_TRACING),)
	dwc3-y				+= trace.o
endif

ifneq ($(filter y,$(CONFIG_USB_DWC3_HOST) $(CONFIG_USB_DWC3_DUAL_ROLE)),)
	dwc3-y				+= host.o
endif

ifneq ($(filter y,$(CONFIG_USB_DWC3_GADGET) $(CONFIG_USB_DWC3_DUAL_ROLE)),)
	dwc3-y				+= gadget.o ep0.o
endif

ifneq ($(CONFIG_USB_DWC3_DUAL_ROLE),)
	dwc3-y				+= drd.o
endif

ifneq ($(CONFIG_USB_DWC3_ULPI),)
	dwc3-y				+= ulpi.o
endif

ifneq ($(CONFIG_DEBUG_FS),)
	dwc3-y				+= debugfs.o
endif

##
# Platform-specific glue layers go here
#
# NOTICE: Make sure your glue layer doesn't depend on anything
# which is arch-specific and that it compiles on all situations.
#
# We want to keep this requirement in order to be able to compile
# the entire driver (with all its glue layers) on several architectures
# and make sure it compiles fine. This will also help with allmodconfig
# and allyesconfig builds.
##

obj-$(CONFIG_USB_DWC3_AM62)		+= dwc3-am62.o
obj-$(CONFIG_USB_DWC3_OMAP)		+= dwc3-omap.o
# Use Samsung's module version
ifndef CONFIG_USB_DWC3_EXYNOS_MODULE
obj-$(CONFIG_USB_DWC3_EXYNOS)		+= dwc3-exynos.o
endif
obj-$(CONFIG_USB_DWC3_PCI)		+= dwc3-pci.o
obj-$(CONFIG_USB_DWC3_HAPS)		+= dwc3-haps.o
obj-$(CONFIG_USB_DWC3_KEYSTONE)		+= dwc3-keystone.o
obj-$(CONFIG_USB_DWC3_MESON_G12A)	+= dwc3-meson-g12a.o
obj-$(CONFIG_USB_DWC3_OF_SIMPLE)	+= dwc3-of-simple.o
obj-$(CONFIG_USB_DWC3_ST)		+= dwc3-st.o
obj-$(CONFIG_USB_DWC3_QCOM)		+= dwc3-qcom.o
obj-$(CONFIG_USB_DWC3_IMX8MP)		+= dwc3-imx8mp.o
obj-$(CONFIG_USB_DWC3_XILINX)		+= dwc3-xilinx.o
obj-$(CONFIG_USB_DWC3_OCTEON)		+= dwc3-octeon.o

# Added from SoC drivers
# SPDX-License-Identifier: GPL-2.0

##
# Platform-specific glue layers go here
#
# NOTICE: Make sure your glue layer doesn't depend on anything
# which is arch-specific and that it compiles on all situations.
#
# We want to keep this requirement in order to be able to compile
# the entire driver (with all its glue layers) on several architectures
# and make sure it compiles fine. This will also help with allmodconfig
# and allyesconfig builds.
##

USB_HDRS="-I${ROOT_DIR}/${KERNEL_DIR}/drivers/usb/dwc3"
USB_LDRS="-I${ROOT_DIR}/${KERNEL_DIR}/include/linux"

ifdef CONFIG_USB_DWC3_EXYNOS_MODULE
subdir-ccflags-y += $(USB_HDRS)
subdir-ccflags-y += $(USB_LDRS)
endif

obj-$(CONFIG_USB_DWC3_EXYNOS_MODULE)		+= dwc3-exynos-usb.o
dwc3-exynos-usb-y			+= dwc3-exynos.o
dwc3-exynos-usb-y			+= dwc3-exynos-otg.o
dwc3-exynos-usb-y			+= dwc3_kret_ops.o
ifneq ($(CONFIG_USB_EXYNOS_TPMON_MODULE),)
	dwc3-exynos-usb-y			+= exynos_usb_tpmon.o
endif
obj-$(CONFIG_SEC_USB_CB)		+= sec_usb_cb.o
obj-$(CONFIG_USB_DEBUG_MODULE)		+= exynos_usb_debug.o
obj-$(CONFIG_EXYNOS_USB_KUNIT_TEST) += test/
